- name: Create Subnet
  amazon.aws.ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    cidr: "{{ ec2_subnet }}"
    tags:
      Environment: "{{ ec2_environment }}"
      Name: "{{ ec2_resource_prefix }}-subnet"
  register: create_subnet
  until: create_subnet is not failed
  retries: 5
